FROM cvat/server:v2.69.0

COPY ./patches/urls.py /home/django/cvat/urls.py
COPY ./patches/cvat-lambdaviews.py /home/django/cvat/apps/lambda_manager/views.py
COPY ./patches/iam-urls.py /home/django/cvat/apps/iam/urls.py
COPY ./patches/cvat-events-handlers.py /home/django/cvat/apps/events/handlers.py
COPY ./patches/cvat-events-utils.py /home/django/cvat/apps/events/utils.py
COPY ./patches/cvat-events-serializers.py /home/django/cvat/apps/events/serializers.py
COPY ./patches/cvat-events-const.py /home/django/cvat/apps/events/const.py
COPY ./patches/access_token_plugin.events.rego /home/django/cvat/apps/access_tokens/rules/access_token_plugin.events.rego
COPY ./settings.py /home/django/settings.py
COPY ./patches/cvat-nginx.conf /etc/nginx/nginx.conf
